### ISSUE TITLE
Sentences (in general) are getting an incorrect sentence_count value

### ISSUE THREAD

**Issue by neomatrix369** [neomatrix369/nlp_profiler#14]
During the presentation, it was observed that sentences with emojis could end up getting an incorrect sentence count. And this could be due to the punctuation(s) that build up emojis.

Note: there may be other edge-cases involving the (.) sign which is the primary indicator of the end of a sentence in English (and many such Latin and Germanic languages).

- [ ] ~_Quick solution_~
- ~Look for emojis in the text, drop them. Then performance sentence counts on the text~
- ~Cache the respective functions so results can be reused.~

- [X] _Better/Robust solution_
- Use a library or existing algorithm that handle edge-cases better. Maybe `nltk` or `spacey` could help in this case. 
- Cache the respective functions so results can be reused.

- [X] _Verify/validate_
- add edge case tests for sentence count

- [X] Apply fix to the dependent functionality 
- Spell check. used it and now it does not help with new less accurate scores, see issue #8 

_Related_
- See #13  and #15, the library/method used may help here

After checking multiple examples it seems many sentences were getting incorrect sentence count.

**Comment by ritikjain51** [comment]
Added an Emoji Decoder

**Comment by neomatrix369** [comment]
The problem detected isn't connected to Emojis, it was an example instance, other types of sentences had this issue too.

**Comment by neomatrix369** [comment]
Fixed by #17 hence closing
