### ISSUE TITLE
Able to run at scale: handle larger datasets

### ISSUE THREAD

**Issue by neomatrix369** [neomatrix369/nlp_profiler#2]
At the moment the library runs slow and takes a long time to handle large datasets due to the processing require per record, this could be optimised and improved in small steps to be able to handle larger datasets

_Opened on the back discussions in #1. Partially related to #3 although independent of the issue._

**Comment by strivedi02** [comment]
I tried to figure out why this whole thing was slow and it turns out the spelling quality operations are slowing it down. And right now I have only checked till high-level analysis still granular level analysis is remaining.
![Screenshot from 2020-09-13 03-03-35](https://user-images.githubusercontent.com/8588143/93013609-852f7b80-f5c7-11ea-9b4a-fbfec572aa1d.png)
I have modified the code a little bit like this:
`#         new_dataframe['spelling_quality_score'] = new_dataframe[text_column].apply(spelling_quality_score)
        for sentence in tqdm_notebook(list(new_dataframe[text_column])):
            spelling_quality_score_list.append(spelling_quality_score(sentence))
        new_dataframe['spelling_quality_score'] = spelling_quality_score_list
`
Am not sure if this is a very efficient method or not but atleast I got to know which line is taking a lot of time.

**Comment by neomatrix369** [comment]
I'm glad you have been able to resolve this temporarily for yourself.

**Comment by neomatrix369** [comment]
> I tried to figure out why this whole thing was slow and it turns out the spelling quality operations are slowing it down. And right now I have only checked till high-level analysis still granular level analysis is remaining.
> ![Screenshot from 2020-09-13 03-03-35](https://user-images.githubusercontent.com/8588143/93013609-852f7b80-f5c7-11ea-9b4a-fbfec572aa1d.png)
> I have modified the code a little bit like this:
> 
> ```
>         for sentence in tqdm_notebook(list(new_dataframe[text_column])):
>             spelling_quality_score_list.append(spelling_quality_score(sentence))
>         new_dataframe['spelling_quality_score'] = spelling_quality_score_list
> ```
> 
> Am not sure if this is a very efficient method or not but atleast I got to know which line is taking a lot of time.

It adds the progress bar which is good but not sure if performance is handled in this manner. For high-level NLP features, it might need to be handled differently.

**Comment by neomatrix369** [comment]
While you think about it and share your thoughts, I will take a look at it and try to improve this aspect of the library

**Comment by neomatrix369** [comment]
> I tried to figure out why this whole thing was slow and it turns out the spelling quality operations are slowing it down. And right now I have only checked till high-level analysis still granular level analysis is remaining.
> ![Screenshot from 2020-09-13 03-03-35](https://user-images.githubusercontent.com/8588143/93013609-852f7b80-f5c7-11ea-9b4a-fbfec572aa1d.png)
> I have modified the code a little bit like this:
> 
> ```
>         for sentence in tqdm_notebook(list(new_dataframe[text_column])):
>             spelling_quality_score_list.append(spelling_quality_score(sentence))
>         new_dataframe['spelling_quality_score'] = spelling_quality_score_list
> ```
> 
> Am not sure if this is a very efficient method or not but atleast I got to know which line is taking a lot of time.

So now that I have looked into this again, and also worked on my implementation, you approach would help get it to use with `tdqm` but speed improvements won't happen till we look at it from parallelising point of view!

**Comment by neomatrix369** [comment]
Some metrics gathered during implementation of this feature, comparing before and after the implementation:


|commit/branch|dataset(rows)|time taken|run by|
|---------------|--------------|----------|-------|
|[master](https://github.com/neomatrix369/nlp_profiler/tree/master) (~ 55c6347) |7 | 6.82 seconds|Mani|
|[master](https://github.com/neomatrix369/nlp_profiler/tree/master) (~ 55c6347) |210 |1min 19s|Mani|
|[master](https://github.com/neomatrix369/nlp_profiler/tree/master) (~ 55c6347) |22000 | 1 hour 24 mins|Kurian|
|[master](https://github.com/neomatrix369/nlp_profiler/tree/master) (~ 55c6347) |?? | ??? seconds/minutes|Virat|
|[master](https://github.com/neomatrix369/nlp_profiler/tree/master) (~ 55c6347) |?? | ??? seconds/minutes|Shubam Trivedi|
|[scale-when-applied-to-larger-datasets](https://github.com/neomatrix369/nlp_profiler/tree/scale-when-applied-to-larger-datasets) (~ a411c13) |7|7.42 seconds|Mani|
|[scale-when-applied-to-larger-datasets](https://github.com/neomatrix369/nlp_profiler/tree/scale-when-applied-to-larger-datasets) (~ a411c13) |210 |39.2 seconds|Mani|
|[scale-when-applied-to-larger-datasets](https://github.com/neomatrix369/nlp_profiler/tree/scale-when-applied-to-larger-datasets) (~ a411c13) |~ 22000| ~ 4 minutes|Kurian|
|[scale-when-applied-to-larger-datasets](https://github.com/neomatrix369/nlp_profiler/tree/scale-when-applied-to-larger-datasets) (~ a411c13) |~ 64000| 16-23 minutes|Mani|
|[scale-when-applied-to-larger-datasets](https://github.com/neomatrix369/nlp_profiler/tree/scale-when-applied-to-larger-datasets) (~ a411c13) |500| ??? seconds/minutes|Virat|
|[scale-when-applied-to-larger-datasets](https://github.com/neomatrix369/nlp_profiler/tree/scale-when-applied-to-larger-datasets) (~ a411c13) |5000| ??? seconds/minutes|Virat|

**Comment by neomatrix369** [comment]
@strivedi02 can you please share your metrics for the above (https://github.com/neomatrix369/nlp_profiler/issues/2#issuecomment-696675059) - please provide info for each and every column possible

**Comment by neomatrix369** [comment]
Closed by PR #9

**Comment by neomatrix369** [comment]
Closed by PR #9

**Comment by kurianbenoy** [comment]
@neomatrix369 for me when applied to scale-when-applied-to-larger-datasets is 4 minutes 37 seconds

Output of %%time
CPU times: user 42.1 s, sys: 747 ms, total: 42.8 s
Wall time: 4min 37s

**Comment by neomatrix369** [comment]
> 4min 37s

Can you please provide the other before and after details like commit ids of the branch you used to install the library? It should not be hard to find out, if you look at the logs it should be there.

**Comment by strivedi02** [comment]
![Screenshot from 2020-09-23 01-30-19](https://user-images.githubusercontent.com/8588143/93937092-d1f02080-fd44-11ea-8d81-db981433bb77.png)
For this above time, the master branch was used and this was tested on colab.

![Screenshot from 2020-09-23 01-42-55](https://user-images.githubusercontent.com/8588143/93937193-f51ad000-fd44-11ea-94cc-8237b88f7adf.png)
and with the same settings the scale-when-applied-to-larger-datasets branch was used.

**Comment by kurianbenoy** [comment]
@neomatrix369 I was running this in Kaggle. The previous experiment with associated time can be found [here](https://www.kaggle.com/kurianbenoy/analysis-for-us-police?scriptVersionId=41723764). I was probably using version 21 of your NLP Profiler Class notebook.

The recent version can be found [here](https://www.kaggle.com/kurianbenoy/analysis-for-us-police). I hope it helps you find the exact version

**Comment by neomatrix369** [comment]
@strivedi02 @kurianbenoy thanks both for the references, you can see above the updated table of the approximate speed ups

**Comment by neomatrix369** [comment]
@strivedi02 thanks for raising the initial discussion #1, and pointers raised about the different issues, this and other issues have been resolved (we still have pending ones but that is fine) as result of user/community feedback and interactions.

**Comment by strivedi02** [comment]
@neomatrix369 I always had to struggle to keep all my scripts in one place or I would have to remember which code is where, but now thanks to you we won't have to remember all that. Through this package, a lot of things will become easy, and I think in the future it will keep growing in terms of usage by the community.

**Comment by neomatrix369** [comment]
> @neomatrix369 I always had to struggle to keep all my scripts in one place or I would have to remember which code is where, but now thanks to you we won't have to remember all that. Through this package, a lot of things will become easy, and I think in the future it will keep growing in terms of usage by the community.

That's really good to know. Glad it helps everyone. It is also what I observed, everyone was using their own recipes, now you can share and contribute and extend a central recipe.

Feel free to open issues/pull requests to extend the existing functionalities to contain additional relevant ones - that is useful for NLP practitioners.

**Comment by neomatrix369** [comment]
@loopyme I'll be happy to hear your feedback on the work done via this issue, please let me know how I can answer your questions and clarify any doubts.

I have tried to build this library from ground-up paying attention to the cohesive modules and structure of the library as a whole.
