### ISSUE TITLE
Not available on Pypi

### ISSUE THREAD

**Issue by getmykhan** [neomatrix369/nlp_profiler#5]
This package is not available on PyPi, plans on when this is going to happen?

- Also provide ways to install directly with `pipenv`

**Comment by neomatrix369** [comment]
> This package is not available on PyPi, plans on when this is going to happen?
> 
> * Also provide ways to install directly with `pipenv`

Good question, making it available on PyPi meaning handling all these extra questions with it, atm I'm trying to keep this library simple and the efforts added to it as well.

**Comment by neomatrix369** [comment]
It is now available on PyPi, see https://pypi.org/project/nlp-profiler/

With regards to your other question, I'll be happy to receive a PR from your good self or someone else to document installing in different environments.

Resolved via branch https://github.com/neomatrix369/nlp_profiler/tree/create-update-release
