### ISSUE TITLE
[BUG] Documentation improvement: Correcting spelling mistakes.

### ISSUE THREAD

**Issue by EpcLoler** [neomatrix369/nlp_profiler#51]
This is a great library with very intuitive features. 
However, while going through the readme files I found a couple of spelling mistakes and text that can be reframed. If you don't mind I would like to pass it through Grammarly and correct it. Let me know your thoughts. Cheers!

**Comment by neomatrix369** [comment]
@EpcLoler please proceed and thank you for raising this

**Comment by neomatrix369** [comment]
It's also okay to just create a Pull Request with the fixes and no need to create an issue for simple issues like this - but thanks again for doing it

**Comment by EpcLoler** [comment]
Sure @neomatrix369 . I will send a PR when I am done

**Comment by neomatrix369** [comment]
We also have the Gitter community where such discussions can take place see https://gitter.im/nlp_profiler/community

**Comment by EpcLoler** [comment]
Thanks for inviting. Sent you the PR. 
Also, would a high level topic modelling method be useful?

**Comment by neomatrix369** [comment]
> Thanks for inviting. Sent you the PR.
> Also, would a high level topic modelling method be useful?

Yes sounds like a good idea, feel free to open a new git issue for it and we can discuss about Topic modelling there.

It's one of the ideas I have in mind too. I'd like to see your take on it and then happy to provide feedback.

**Comment by neomatrix369** [comment]
Closing as fulfilled via PR #52
